version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          REVIEWDOG_VERSION: "0.9.11"

    working_directory: /go/src/github.com/ohatakky/circleci-sample
    steps:
      - checkout

      - run: curl -fSL https://github.com/reviewdog/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - run: go vet ./... 2>&1 | ./reviewdog -f=govet -reporter=github-pr-review
